version: '3.8'

services: 
    app:
        container_name: dummy_server
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "80:9000"
        volumes: 
            - ./source:/usr/src/app          